### PR TITLE
added commas in subsector and additional currency

### PR DESCRIPTION
**Pull request by felskia**

### CODE REVIEW

**Comment by felskia** [comment]
@kamicut I added the commas to one of the subsectors but the commas aren't actually showing up in the backend. I'm not sure when the IFPRI folks are showing off the tool so if this has the potential for messing anything up let's not push it until we know.

**Comment by kamicut** [comment]
@felskia do you mean to say that your locally hosted version is not showing your changes? That's odd. I'll pull down the changes and check.

**Comment by felskia** [comment]
@kamicut that is correct. My local version it's not showing up. :) Let me know what you see and thanks!

**Comment by kamicut** [comment]
This works for me locally.

**Pull request merged**
